include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: 
    - [build/**]
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/**/*.reflectable.dart
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - camel_case_types
    - prefer_const_declarations