name: article
description: A new flutter plugin project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  retrofit: any
  kt_dart: ^0.10.0
  flutter_bloc: ^8.0.1
  json_annotation: ^4.1.0
  freezed_annotation: ^1.1.0
  dartz: ^0.10.0-nullsafety.2
  engine:
    path: ../engine
  theme_manager:
    path: ../theme_manager
  postman_dio: 1.0.2
  logger: any
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any
  lint: ^1.5.3
  freezed: ^1.1.1
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  retrofit_generator: any
  json_serializable: ^6.1.4

flutter:
