import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:theme_manager/theme_manager.dart';
import 'package:app_user/injection.dart';
import 'package:app_user/module/service/service.dart';
import 'package:app_user/presentation/routes/routes.dart';
part 'categories.dart';
part 'categories_page.dart';
part 'category_tile.dart';
