import 'dart:io' as io;
import 'package:carousel_slider/carousel_slider.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:image_picker/image_picker.dart';
import 'package:theme_manager/theme_manager.dart';
import 'package:app_user/core/core.dart';
import 'package:app_user/i18n/i18n.dart';
import 'package:app_user/injection.dart';
import 'package:app_user/module/article/article.dart';
import 'package:app_user/module/auth/auth.dart';
import 'package:app_user/module/catalogue/catalogue.dart';
import 'package:app_user/module/file/file.dart' hide Image;
import 'package:app_user/module/option/option.dart';
import 'package:app_user/module/service/service.dart';
import 'package:app_user/presentation/article/article.dart';
import 'package:app_user/presentation/category/category.dart';
import 'package:app_user/presentation/image_selector/image_selector_small.dart';
import 'package:app_user/presentation/routes/routes.dart';
import 'package:app_user/presentation/service/service.dart';
part 'home_banner.dart';
part 'home_page.dart';
part 'home_upload_file.dart';
