import 'dart:io';

import 'package:auto_route/auto_route.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:image_picker/image_picker.dart';
import 'package:theme_manager/theme_manager.dart';
import 'package:app_user/i18n/i18n.dart';
import 'package:app_user/injection.dart';
import 'package:app_user/module/cart/cart.dart';
import 'package:app_user/module/favorite/favorite.dart';
import 'package:app_user/module/service/service.dart';
import 'package:app_user/presentation/routes/router.gr.dart';
import '../../service/services/service_tile.dart';
part 'cart_images_selector.dart';
part 'cart_item_update_form.dart';
part 'cart_item_update_page.dart';
