name: theme_manager
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  json_annotation: ^4.1.0
  freezed_annotation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  lint: ^1.5.3
  freezed: ^1.1.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  mockito: any


flutter:
