import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:theme_manager/theme_manager.dart';
import 'package:app_user/i18n/i18n.dart';
import 'package:app_user/injection.dart';
import 'package:app_user/module/auth/auth.dart';
import 'package:app_user/presentation/widgets.dart';
part 'password_update_form.dart';
part 'password_update_page.dart';
