name: app_user
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: any
  dio: ^4.0.4
  retrofit: any
  get_it: ^7.2.0
  rxdart: ^0.27.3
  kt_dart: ^0.10.0
  injectable: ^1.4.1
  auto_route: ^3.2.4
  postman_dio: ^1.0.2
  flutter_bloc: ^8.0.1
  json_annotation: ^4.1.0
  cupertino_icons: ^1.0.2
  freezed_annotation: ^1.1.0
  dartz: ^0.10.0-nullsafety.2
  firebase_auth: ^3.3.5
  firebase_core: ^1.3.0
  google_sign_in: ^5.0.4
  cloud_firestore: ^3.1.6
  flutter_rating_bar: ^4.0.0
  flutter_secure_storage: ^5.0.2
  flutter_html: ^2.2.1
  refresh_loadmore: ^2.0.5
  theme_manager:
    path: ../theme_manager
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any
  lint: ^1.5.3
  freezed: ^1.1.1
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.4
  injectable_generator: ^1.5.3
  auto_route_generator: ^3.2.3
  retrofit_generator: any

flutter:
  uses-material-design: true