name: app_user
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: any
  dio: ^4.0.4
  retrofit: any
  get_it: ^7.2.0
  kt_dart: ^0.10.0
  injectable: ^1.4.1
  auto_route: ^3.2.4
  postman_dio: ^1.0.2
  flutter_bloc: ^8.0.1
  json_annotation: ^4.1.0
  cupertino_icons: ^1.0.2
  freezed_annotation: ^1.1.0
  dartz: ^0.10.0-nullsafety.2
  article:
    path: ../article
  auth:
    path: ../auth
  booking:
    path: ../booking
  engine:
    path: ../engine
  service:
    path: ../service
  theme_manager:
    path: ../theme_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any
  lint: ^1.5.3
  freezed: ^1.1.1
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.4
  injectable_generator: ^1.5.3
  auto_route_generator: ^3.2.3

flutter:
  uses-material-design: true