name: service_example
description: Demonstrates how to use the service plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger: any
  dio: ^4.0.4
  postman_dio: 1.0.2
  cupertino_icons: ^1.0.2
  service:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true